FROM nginx
USER root
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./miniserver.c /home/miniserver.c
COPY ./s.sh /home/entrypoint.sh
RUN chmod +x /home/entrypoint.sh
RUN apt-get update && apt install -y gcc spawn-fcgi libfcgi-dev
WORKDIR /home/
CMD ["./entrypoint.sh"]